env:
  commonjs: true
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 13
rules:
  no-console: ['error', { 'allow': ['warn', 'error', 'info', 'dir'] }]
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
